bursary_app/urls.py
from django.urls import path
from bursary_app import views

app_name = 'bursary_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('profile', views.ApplicantProfileView.as_view(), name='profile'),
    path('register', views.ApplicantRegisterView.as_view(), name='register'),
    path('login', views.LoginView.as_view(), name='login'),
    path('profile/edit', views.ApplicantCreateView.as_view(), name='edit_profile'),
    path('logout', views.LogoutView.as_view(), name='logout'),
]

bursary_online/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bursary_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

theme/templates/base.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
    	<title>{% block title %}WELCOME|Bursary-Online{% endblock %}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-grey-lightest font-serif leading-normal tracking-normal">
		<header class="sticky top-0 z-20 bg-blue-100">
			{% block header %}
        <div class="container flex md:grid md:grid-cols-3 md:auto-cols-min">
          <div class="inline-flex md:col-span-2">
            <a href="{% url 'bursary_app:index' %}" class="p-2">
              <img src="{% static 'theme/images/workflow-logo.png' %}" alt="site logo" 
                class="object-scale-down h-8 w-full">
            </a>
            <h1 class="p-2">
              <a href="{% url 'bursary_app:index' %}">Bursary-Online</a>
            </h1>
          </div>
          <div class="md:justify-self-end p-2">
            {% if user.is_authenticated %}
              <ul>
                <li>
                  Logged in as: 
                  <a href="">{{ user.get_username }}</a>
                </li>
                <li>
                  <a href="{% url 'bursary_app:logout' %}">Logout</a>
                </li>
              </ul>
            {% else %}
              <a href="{% url 'bursary_app:register' %}" class="md:p-2">Register</a>
              <a href="{% url 'bursary_app:login' %}" class="md:p-2">Log In</a>
            {% endif %}
          </div>
          <div class="block md:hidden justify-self-end">
            <button class="flex items-center px-4 py-3 border rounded text-teal-500 border-teal-500 focus:outline-none">
              <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                  <title>Menu</title>
                  <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
              </svg>
            </button>
          </div>
        </div>
      {% endblock %}
		</header>
		{% block content %}
			<div class="container mx-auto">
				<section class="flex items-center justify-center h-screen">
					<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
				</section>
			</div>
		{% endblock content %}

	</body>
</html>

theme/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="relative bg-white overflow-hidden">
  <div class="max-w-7xl mx-auto">
    <div class="relative z-10 pb-8 bg-white sm:pb-16 md:pb-20 lg:max-w-2xl lg:w-full lg:pb-28 xl:pb-32">
      <svg class="hidden lg:block absolute right-0 inset-y-0 h-full w-48 text-white transform translate-x-1/2" 
      fill="currentColor" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">
        <polygon points="50,0 100,0 50,100 0,100" />
      </svg>

      <div>
        <div class="relative pt-6 px-4 sm:px-6 lg:px-8">
          <nav class="relative flex items-center justify-between sm:h-10 lg:justify-start" aria-label="Global">
            <div class="flex items-center flex-grow flex-shrink-0 lg:flex-grow-0">
              <div class="flex items-center justify-between w-full md:w-auto">
                <div class="-mr-2 flex items-center md:hidden">
                  <button type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-expanded="false">
                    <span class="sr-only">Open main menu</span>
                    <!-- Heroicon name: outline/menu -->
                    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                    </svg>
                  </button>
                </div>
              </div>
            </div>
            <div class="hidden group md:block md:ml-10 md:pr-4 md:space-x-8">
              <a href="{% url 'bursary_app:index' %}" class="font-medium text-gray-500 hover:text-gray-900 visited:text-pink-600">Home</a>

              <a href="#" class="font-medium text-gray-500 hover:text-gray-900 visited:text-pink-600">Application Portal</a>

              <a href="#" class="font-medium text-gray-500 hover:text-gray-900 visited:text-pink-600">News and Events</a>

              <a href="#" class="font-medium text-gray-500 hover:text-gray-900 visited:text-pink-600">Downloads</a>

              <a href="{% url 'admin:login' %}" class="font-medium text-indigo-600 hover:text-indigo-500 visited:text-pink-600">Staff</a>
            </div>
          </nav>
        </div>

        <!--
          Mobile menu, show/hide based on menu open state.

          Entering: "duration-150 ease-out"
            From: "opacity-0 scale-95"
            To: "opacity-100 scale-100"
          Leaving: "duration-100 ease-in"
            From: "opacity-100 scale-100"
            To: "opacity-0 scale-95"
        -->
        <div class="absolute z-10 top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden">
          <div class="rounded-lg shadow-md bg-white ring-1 ring-black ring-opacity-5 overflow-hidden">
            <div class="px-5 pt-4 flex items-center justify-between">
              <div>
                <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="">
              </div>
              <div class="-mr-2">
                <button type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
                  <span class="sr-only">Close main menu</span>
                  <!-- Heroicon name: outline/x -->
                  <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>
            <div class="px-2 pt-2 pb-3 space-y-1">
              <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50">Home</a>

              <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50">Application portal</a>

              <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50">News and Events</a>

              <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50">Staff</a>
            </div>
            <a href="#" class="block w-full px-5 py-3 text-center font-medium text-indigo-600 bg-gray-50 hover:bg-gray-100">
              Log in
            </a>
          </div>
        </div>
      </div>

      <main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
        <div class="sm:text-center lg:text-left">
          <h1 class="text-4xl tracking-tight font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
            <span class="block xl:inline">Empowering your dreams.</span>
            <span class="block text-indigo-600 xl:inline">Securing our future.</span>
          </h1>
          <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
            Everyone has a right to education. We enable needy students get educated, gain skills.    
          </p>
          <div class="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start">
            <div class="rounded-md shadow">
              <a href="#" class="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 md:py-4 md:text-lg md:px-10">
                Get started
              </a>
            </div>
            <div class="mt-3 sm:mt-0 sm:ml-3">
              <a href="#" class="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 md:py-4 md:text-lg md:px-10">
                Check status
              </a>
            </div>
          </div>
        </div>
      </main>
    </div>
  </div>
  <div class="lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
    <img class="h-56 w-full object-cover sm:h-72 md:h-96 lg:w-full lg:h-full" src="{% static 'theme/images/grad.jpg' %}" alt="">
  </div>
</div>

{% endblock  %}